# Generated by Django 4.2.7 on 2025-06-27 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discounted_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('rating', models.FloatField(blank=True, null=True)),
                ('reviews_count', models.IntegerField(default=0)),
                ('url', models.URLField(max_length=500)),
                ('query', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['price'], name='WBParser_pr_price_1035bb_idx'), models.Index(fields=['rating'], name='WBParser_pr_rating_eb88a1_idx'), models.Index(fields=['reviews_count'], name='WBParser_pr_reviews_dd6b6f_idx')],
            },
        ),
    ]
