# Generated by Django 4.2.7 on 2025-06-27 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WBParser', '0002_product_updated_at_product_wb_id_alter_product_name'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='product',
            name='WBParser_pr_price_1035bb_idx',
        ),
        migrations.RemoveIndex(
            model_name='product',
            name='WBParser_pr_rating_eb88a1_idx',
        ),
        migrations.RemoveIndex(
            model_name='product',
            name='WBParser_pr_reviews_dd6b6f_idx',
        ),
    ]
