# Generated by Django 4.2.7 on 2025-06-27 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WBParser', '0003_remove_product_wbparser_pr_price_1035bb_idx_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='product',
            table='wildberries_products',
        ),
    ]
