# Generated by Django 4.2.7 on 2025-06-27 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WBParser', '0004_alter_product_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='product',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='product',
            name='wb_id',
            field=models.BigIntegerField(unique=True),
        ),
    ]
