# Generated by Django 4.2.7 on 2025-06-27 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WBParser', '0005_alter_product_options_remove_product_updated_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WildberriesProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search_query', models.CharField(max_length=255)),
                ('products', models.JSONField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
